import time

# List of lyrics
ajj_din_chadheya_lyrics = [
    "Ajj din chadheya",
    "Tere rang warga",
    "Ajj din chadheya",
    "Tere rang warga",
    "",
    "Phul sa hai khila",
    "aaj din",
    "Rabba mere din yeh",
    "na dhale",
    "Woh jo mujhe khawab",
    "mein mile",
    "",
    "Use tu lagede abb gale",
    "Tenu dil da vasta",
    "Rabba aaya dar de yaar de",
    "Sara jahan chod chad ke",
    "Mere sapne sawar de",
    "Tennu dil da vasta",
    "",
    "Ajj din chadheya",
    "Tere rang warga",
    "",
    "Baksha gunaho ko",
    "Sun ke duwao ko",
    "Rabba pyaar hai",
    "Tune sab ko hi de diya",
    "Meri bhi aahon ko",
    "Sun le duwao ko",
    "Mujhko woh dila mene",
    "jisko hai dil diya",
    "Hoooo",
    "",
    "Baksha gunaho ko",
    "Sun ke duwao ko",
    "Rabba pyaar hai",
    "Tune sab ko hi de diya",
    "Meri bhi aahon ko",
    "Sun le duwao ko",
    "Mujhko woh dila mene",
    "jisko hai dil diya",
    "",
    "Aasmaan pe aasmaan",
    "uske de itna bata",
    "Woh jo mujhko dekh",
    "ke hase",
    "Pana chahun raat din",
    "jise",
    "Rabba mere naam",
    "kar use",
    "Tenu dil da vasta",
    "",
    "Ajj din chadheya",
    "Tere rang warga",
    "",
    "Manga jo mera hai",
    "Jata kya tera hai",
    "Mene kaun si",
    "Tujhse jannat manga li",
    "Kaisa khuda hai tu",
    "Bas naam ka hai tu",
    "Rabba jo teri itni",
    "si bhi na chali",
    "Haaanaaa",
    "",
    "Manga jo mera hai",
    "Jata kya tera hai",
    "Mene kaun si",
    "Tujhse jannat manga li",
    "Kaisa khuda hai tu",
    "Bas naam ka hai tu",
    "Rabba jo teri itni",
    "si bhi na chali",
    "",
    "Chahiye jo mujhe",
    "Kar de tu mujhko ata",
    "Jeeti rahi saltanat teri",
    "Jeeti rahe ashiqui meri",
    "Dede mujhe zindagi meri",
    "Tenu dil da vasta",
    "",
    "Rabba mere din yeh",
    "na dhale",
    "Woh jo mujhe khawab",
    "mein mile",
    "Use tu lagede abb gale",
    "Tenu dil da vasta",
    "",
    "Rabba aaya dar de yaar de",
    "Sara jahan chod chad ke",
    "Mere sapne sawar de",
    "Tennu dil da vasta",
    "",
    "Ajj din chadheya",
    "Tere rang warga",
    "Ajj din chadheya",
    "Tere rang warga",
    "Ajj din chadheya",
    "Tere rang warga",
    "Din chadheya",
    "Tere rang warga",
    "Ajj din chadheya",
]

# Function to display the lyrics with time delay
def display_lyrics_with_delay(lyrics, delay=2):
    for line in lyrics:
        print(line)
        if line.strip():  # Add a delay only for non-empty lines
            time.sleep(delay)

# Call the function to display the lyrics with time delay
if __name__ == "__main__":
    print("Playing lyrics...\n")
    display_lyrics_with_delay(ajj_din_chadheya_lyrics, delay=2)
